PW Skills Assignment Solutions
Assignment-Numpy

Q1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [1]:
import numpy as np
import pandas as pd

In [4]:
import numpy as np
arr=np.arange(6)
print(arr)
print(type(arr))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


Q2.  Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])

In [5]:
arr = np.array([1.5, 2.6, 3.7])
print(type(arr))

<class 'numpy.ndarray'>


Q3.  Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [13]:
arr = np.array([1+2j, 3-4j, 5+6j], dtype=np.complex128)
print(arr)
print(type(arr))

[1.+2.j 3.-4.j 5.+6.j]
<class 'numpy.ndarray'>


 Q4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [15]:
arr=np.array([1,3,5,7], dtype=np.float32)
print(arr)
print(type(arr))

[1. 3. 5. 7.]
<class 'numpy.ndarray'>


Q5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [25]:
arr = np.array([1.51, 2.67, 3.72], dtype=np.float64)
print(arr)
arr1=np.array(arr, dtype=np.float32)
print(arr1)

[1.51 2.67 3.72]
[1.51 2.67 3.72]


Q6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
type.

In [35]:
def array_attributes(arr):
    print("Shape of array is", np.shape(arr))
    print("Size of array is", np.size(arr))
    print("Data Type of array is", arr.dtype)
    
arr=np.array([1,2,4,6,8,9])
array_attributes(arr)

arr=np.array([1.23,2.57,4.68,6.11])
array_attributes(arr)

Shape of array is (6,)
Size of array is 6
Data Type of array is int64
Shape of array is (4,)
Size of array is 4
Data Type of array is float64


Q7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [42]:
def array_dimension(arr):
    print("Dimentionality of array is", arr.ndim)

arr=np.array([3,2,4,5,8,9])
array_dimension(arr)

arr=np.array([[1,2,3],[4,5,6]])
array_dimension(arr)

Dimentionality of array is 1
Dimentionality of array is 2


Q8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.

In [44]:
def item_size_info(arr):
    print("The item size is", arr.itemsize,"bytes")
    print("The total size is", arr.nbytes,"bytes")
        
arr=np.array([3,2,4])
item_size_info(arr)

arr=np.array([[1,2,3],[4,5,6]])
item_size_info(arr)

The item size is 8 bytes
The total size is 24 bytes
The item size is 8 bytes
The total size is 48 bytes


Q9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [8]:
def array_strides(arr):
    return "The strides of array is", arr.strides

arr=np.array([3,2,4])
array_strides(arr)

('The strides of array is', (8,))

Q10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array.

In [9]:
def shape_stride_relationship(arr):
    print("The shape of array is", np.shape(arr))
    print("The strides of array is", arr.strides)
    
arr=np.array([1.23,2.57,4.68,6.11])
shape_stride_relationship(arr)

The shape of array is (4,)
The strides of array is (8,)


Q11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements.

In [12]:
def create_zeros_array(n):
    return np.array([0 for i in range (n)])

n=int(input("Enter an integer number to generate array of zeros with 'n' elements"))
create_zeros_array(n)


Enter an integer number to generate array of zeros with 'n' elements 5


array([0, 0, 0, 0, 0])

Q12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`.

In [15]:
def create_ones_matrix(rows, cols):
    return np.ones((rows,cols))

print("For creating a matrix of ones enter the following details:")
r=int(input("Enter the number of rows:"))
c=int(input("Enter the number of columns:"))
create_ones_matrix(r,c)

For creating a matrix of ones enter the following details:


Enter the number of rows: 2
Enter the number of columns: 3


array([[1., 1., 1.],
       [1., 1., 1.]])

Q13.Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.

In [20]:
def generate_range_array(start, stop, step):
    return np.array([i for i in range(start, stop, step)])


start=int(input("Enter any integer value for starting element of the array:"))
stop=int(input("Enter any integer value for end value of the array:"))
step=int(input("Enter any integer value for step between each element of the array:"))
generate_range_array(start, stop, step)

Enter any integer value for starting element of the array: 4
Enter any integer value for end value of the array: 15
Enter any integer value for step between each element of the array: 2


array([ 4,  6,  8, 10, 12, 14])

Q14.  Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).

In [21]:
def generate_linear_space(start, stop, num):
    return np.linspace(start,stop,num)

start=float(input("Enter any float value for starting element of the array:"))
stop=float(input("Enter any float value for end value of the array:"))
num=int(input("Enter any integer value for generating n equally spaced values between `start` and `stop':"))

generate_linear_space(start, stop, num)

Enter any float value for starting element of the array: 2.4
Enter any float value for end value of the array: 10.4
Enter any integer value for generating n equally spaced values between `start` and `stop': 5


array([ 2.4,  4.4,  6.4,  8.4, 10.4])

Q15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.

In [3]:
def create_identity_matrix(n):
    return np.eye(n)

n=int(input("Enter an integer value for size of identity matrix:"))
create_identity_matrix(n)

Enter an integer value for size of identity matrix: 4


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Q16. Write a function that takes a Python list and converts it into a NumPy array.

In [7]:
def convert_to_array(lst):
    return np.array(lst)

lst=[3,5,7,12,20]
convert_to_array(lst)

array([ 3,  5,  7, 12, 20])

Q17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.

In [13]:
import numpy as np

# Create a NumPy array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Create a view of the original array
view_array = original_array.view()

# Modify the view array
view_array[0, 0] = 100

print("Original array:")
print(original_array)

print("\nView array:")
print(view_array)


Original array:
[[100   2   3]
 [  4   5   6]]

View array:
[[100   2   3]
 [  4   5   6]]


Q18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [26]:
def concatenate_array(arr1,arr2, n):
    return np.concatenate((arr1,arr2), axis=n)

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

concatenate_array(arr1,arr2, 0) #contenating with axis=0 horizontaly

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
concatenate_array(arr1,arr2, 1) #contenating with axis=1 vertically

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Q19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

In [28]:
arr1=np.array([[1,2],[3,4],[9,10]])
arr2=np.array([[5,6],[7,8]])
np.concatenate((arr1,arr2), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 9, 10],
       [ 5,  6],
       [ 7,  8]])

Q20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [31]:
def array_stacking(*arr):
    stacked_array = np.vstack((arr))
    return"\nVertically stacked arrays:\n", stacked_array

arr1=np.array([[1,2],[3,4],[5,6]])
arr2=np.array([[7,8],[9,10]])
arr3=np.array([11,12])
array_stacking(arr1,arr2,arr3)

('\nVertically stacked arrays:\n',
 array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]]))

Q21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size.

In [33]:
def int_array(start,stop,step):
    return np.array([i for i in range(start,stop+1,step)])

start=int(input("Enter any integer value for starting element of the array:"))
stop=int(input("Enter any integer value for end value of the array:"))
step=int(input("Enter any integer value for step between each element of the array:"))
int_array(start,stop,step)

Enter any integer value for starting element of the array: 2
Enter any integer value for end value of the array: 11
Enter any integer value for step between each element of the array: 3


array([ 2,  5,  8, 11])

Q22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).

In [34]:
def gen_array():
    return np.linspace(0,1,10)

gen_array()

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Q23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive).

In [5]:
def log_generator():
    return np.logspace(1,1000,num=5)
    
log_generator()

array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

Q24.Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.

In [9]:
# Generate a 5x3 NumPy array with random integers between 1 and 100
data_array = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame from the NumPy array
df1=pd.DataFrame(data_array)
print(df1)

    0   1   2
0  62   3  53
1  88  54   9
2  81  90  71
3  17  30  89
4  41  28  89


Q25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.

In [10]:
def replace_negatives_with_zeros(df, column_name):
    
    # Use np.where() to replace negative values with zeros in the specified column
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    
    return df


df = pd.DataFrame({'A': [-1, 2, -3, 4, -5],
                   'B': [6, -7, 8, -9, 10]})

# Replace negative values with zeros in column 'A'
df_updated = replace_negatives_with_zeros(df, 'A')

print("Original DataFrame:")
print(df)
print("\nDataFrame with negative values replaced by zeros:")
print(df_updated)


Original DataFrame:
   A   B
0  0   6
1  2  -7
2  0   8
3  4  -9
4  0  10

DataFrame with negative values replaced by zeros:
   A   B
0  0   6
1  2  -7
2  0   8
3  4  -9
4  0  10


Q26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

In [11]:
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [12]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[(1,2)]

6

28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])

In [13]:
arr = np.array([3, 8, 2, 10, 5, 7])
greater_than_5 = arr[arr > 5]
print("Elements greater than 5:", greater_than_5)

Elements greater than 5: [ 8 10  7]


29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr1=arr[2:6]
print(arr1)

[3 4 5 6]


30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [16]:
arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

Q31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array

In [19]:
def extract_elements_by_indices(arr, indices):
    
    # Use fancy indexing to extract elements from arr based on indices
    extracted_elements = arr[indices]
    
    return extracted_elements


arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

indices = np.array([0, 2, 1])  # Indices to extract elements in the order [0, 2, 1]

# Extract elements from arr based on indices
extracted_elements = extract_elements_by_indices(arr, indices)

print("Extracted elements based on indices:", extracted_elements)


Extracted elements based on indices: [[1 2 3]
 [7 8 9]
 [4 5 6]]


32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.

In [18]:
arr = np.array([3, 8, 2, 10, 5, 7,9,2,3,11])
Threshold = arr[arr > 5]
print("Elements greater than 5:", Threshold)

Elements greater than 5: [ 8 10  7  9 11]


33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.

In [21]:
def extract_element(array_3d, x,y,z):
    extracted_element=array_3d[x,y,z]
    return extracted_element
    
arr = np.array([[[1, 2, 3],
                 [4, 5, 6]],
                [[7, 8, 9],
                 [10, 11, 12]]])

x = np.array([0, 1])  # Indices for the first dimension
y = np.array([0, 1])  # Indices for the second dimension
z = np.array([0, 2])  # Indices for the third dimension

# Extract elements from arr based on indices
extracted_elements = extract_element(arr, x,y,z)

print("Extracted elements:", extracted_elements)

Extracted elements: [ 1 11]


34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing.

In [22]:
def elements_satisfying_conditions(arr, condition1, condition2):
    
    elements = arr[(condition1) & (condition2)]
    
    return elements


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
condition1 = arr > 4  # First condition: elements greater than 2
condition2 = arr % 2 == 0  # Second condition: even elements

# Get elements that satisfy both conditions
result = elements_satisfying_conditions(arr, condition1, condition2)

print("Elements satisfying both conditions:", result)


Elements satisfying both conditions: [ 6  8 10]


35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.

In [23]:
def extract_element(array_2d, row, col):
    extracted_element=array_2d[row,col]
    return extracted_element
    
arr = np.array([[1, 2, 3],
                 [4, 5, 6]])

row = np.array([0, 1])  
col= np.array([0, 1])  


# Extract elements from arr based on indices
extracted_elements = extract_element(arr, row, col)

print("Extracted elements:", extracted_elements)

Extracted elements: [1 5]


36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [28]:
arr=np.ones((3,3))
res=arr+5
print(res)

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.

In [33]:
arr1=np.array([1,2,3])
arr2=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
arr1_reshaped = arr1.reshape(3, 1) #reshaping array1 for multiplying with each row of array2
res=arr2*arr1_reshaped
print(res)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.

In [38]:
arr_1d=np.array([1,2,3,4])
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [10,11,12]])
res=arr_1d.reshape(4,1)+arr_2d
print(res)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [ ]:
39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.

In [42]:
arr1=np.array([[1],[2],[3]]) #array(3,1)
arr2=np.array([1,2,3]) #array(1,3)
res=arr1+arr2
print(res)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.

In [53]:
arr1=np.array([[1,2,3],
              [4,5,6]])
arr2=np.array([[2,2],
              [2,2]])
rarr1=arr1.reshape(3,2)
res=rarr1@arr2
print(res)

[[ 6  6]
 [14 14]
 [22 22]]


41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [58]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.mean(axis=0)

array([2.5, 3.5, 4.5])

42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [57]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.mean(axis=1)

array([2., 5.])

43. For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [59]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.max(axis=0)

array([4, 5, 6])

44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [63]:
def moving_sum_along_rows(arr):
    # Initialize an empty list to store the moving sum results
    moving_sums = []
    
    # Iterate over each row in the array
    for row in arr:
        # Initialize an empty list to store the moving sum for the current row
        row_moving_sum = []
        
        # Initialize a variable to store the cumulative sum
        cumulative_sum = 0
        
        # Iterate over each element in the row
        for element in row:
            # Add the current element to the cumulative sum
            cumulative_sum += element
            
            # Append the cumulative sum to the row_moving_sum list
            row_moving_sum.append(cumulative_sum)
        
        # Append the row_moving_sum list to the moving_sums list
        moving_sums.append(row_moving_sum)
    
    # Convert the moving_sums list to a NumPy array and return it
    return np.array(moving_sums)

# Given array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate the moving sum along rows using the custom function
result = moving_sum_along_rows(arr)

print("Original array:")
print(arr)
print("\nMoving sum along rows (custom function):")
print(result)


Original array:
[[1 2 3]
 [4 5 6]]

Moving sum along rows (custom function):
[[ 1  3  6]
 [ 4  9 15]]


45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])

In [65]:
arr = np.array([[2, 4, 6], [8, 5, 7]])
all_even_columns = np.all(arr % 2 == 0, axis=0)
print(all_even_columns)

[ True False False]


46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])

In [69]:
original_array = np.array([1, 2, 3, 4, 5, 6])
print(original_array.reshape(6,1))
print("\n",original_array.reshape(3,2))
print("\n",original_array.reshape(2,3))
print("\n",original_array.reshape(2,1,3))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

 [[1 2]
 [3 4]
 [5 6]]

 [[1 2 3]
 [4 5 6]]

 [[[1 2 3]]

 [[4 5 6]]]


47. Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [70]:
def flatten_matrix(input_matrix):
    
    return input_matrix.flatten()

# Given input matrix
input_matrix = np.array([[1, 2, 3],
                         [4, 5, 6]])

# Flatten the matrix
flattened_array = flatten_matrix(input_matrix)

print("Input matrix:")
print(input_matrix)
print("\nFlattened array:")
print(flattened_array)


Input matrix:
[[1 2 3]
 [4 5 6]]

Flattened array:
[1 2 3 4 5 6]


48. Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

In [72]:
def concatenate_array(arr1,arr2, n):
    return np.concatenate((arr1,arr2), axis=n)

array1=np.array([[1,2],[3,4]])
array2=np.array([[5,6],[7,8]])

concatenate_array(array1,array2, 0) #concatenate along axis=0


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [73]:
concatenate_array(array1,array2, 1) #concatenate along axis=1

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Q49.Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [75]:
def split_array(arr,split_num,axis):
    return np.split(arr,split_num,axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
split_array(original_array,3,0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [76]:
split_array(original_array,3,1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

Q50.  Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

In [78]:
def func(arr,indices_to_insert,values_to_insert,indices_to_delete):
    print("The original array", arr)
    inserted_arr=np.insert(arr,indices_to_insert,values_to_insert)
    print("The new array with values inserted at specified indices",inserted_arr)
    del_arr=np.delete(inserted_arr,indices_to_delete)
    print("The array after deleting specified indices",del_arr)
    

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
func(original_array,indices_to_insert,values_to_insert,indices_to_delete)

The original array [1 2 3 4 5]
The new array with values inserted at specified indices [ 1  2 10  3  4 11  5]
The array after deleting specified indices [ 1 10  4 11  5]


51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.

In [84]:
arr1=np.array([np.random.rand(1,2)])
print(arr1)
arr2=np.array([i for i in range(1,11)])
print("\n",arr2)
res=arr1.reshape(2,1)+arr2
print("\n",res)

[[[0.35781581 0.8354861 ]]]

 [ 1  2  3  4  5  6  7  8  9 10]

 [[ 1.35781581  2.35781581  3.35781581  4.35781581  5.35781581  6.35781581
   7.35781581  8.35781581  9.35781581 10.35781581]
 [ 1.8354861   2.8354861   3.8354861   4.8354861   5.8354861   6.8354861
   7.8354861   8.8354861   9.8354861  10.8354861 ]]


Q52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [86]:
arr1=np.array([i for i in range(10,0,-1)])
print(arr1)
arr2=np.array([i for i in range(1,11)])
print("\n",arr2)
res=arr1-arr2
print("\n",res)

[10  9  8  7  6  5  4  3  2  1]

 [ 1  2  3  4  5  6  7  8  9 10]

 [ 9  7  5  3  1 -1 -3 -5 -7 -9]


Q53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.

In [87]:
arr1=np.array([np.random.rand(2,1)])
print(arr1)
arr2=np.array([i for i in range(1,6)])
print("\n",arr2)
res=arr1*arr2
print("\n",res)

[[[0.22434785]
  [0.83934999]]]

 [1 2 3 4 5]

 [[[0.22434785 0.44869569 0.67304354 0.89739138 1.12173923]
  [0.83934999 1.67869997 2.51804996 3.35739994 4.19674993]]]


Q54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.

In [88]:
arr1=np.array([i for i in range(2,11) if i%2==0])
print(arr1)
arr2=np.array([i for i in range(1,6)])
print("\n",arr2)
res=arr1/arr2
print("\n",res)

[ 2  4  6  8 10]

 [1 2 3 4 5]

 [2. 2. 2. 2. 2.]


Q55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [93]:
arr1=np.arange(1,6)
print(arr1)
arr2=np.flip(arr1)
print("\n",arr2)
res=np.power(arr1,arr2)
print("\n",res)


[1 2 3 4 5]

 [5 4 3 2 1]

 [ 1 16 27 16  5]


Q56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [2]:
def count_substring(arr, subs):
    count=0
    for s in arr:
        count+=s.count(subs)
    return count

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
subs='hello'
count_substring(arr, subs)

3

Q57. Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [7]:
def upper_case(arr):
    lst=[]
    for s in arr:
        for i in s:
            if i.isupper()==True:
                lst.append(i)
    return lst

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
upper_case(arr)

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']

Q58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [8]:
def replace_substring(arr, old_substring, new_substring):
    
    return np.array([s.replace(old_substring, new_substring) for s in arr])

# Given NumPy array of strings
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Substring to be replaced and new substring
old_substring = 'apple'
new_substring = 'orange'

# Replace occurrences of old_substring with new_substring in the array
result = replace_substring(arr, old_substring, new_substring)

print("Original array:")
print(arr)
print("\nAfter replacement:")
print(result)


Original array:
['apple' 'banana' 'grape' 'pineapple']

After replacement:
['orange' 'banana' 'grape' 'pineorange']


Q59. Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [9]:
def concat(arr1,arr2):
    return arr1[0]+arr1[1], arr2[0]+arr2[1]
        
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
concat(arr1,arr2)

('HelloWorld', 'OpenAI')

In [10]:
def concatenate_strings(arr1, arr2):
    
    # Check if both arrays have the same shape
    if arr1.shape != arr2.shape:
        raise ValueError("Arrays must have the same shape for element-wise concatenation.")
    
    # Concatenate strings element-wise using list comprehension
    concatenated_array = np.array([s1 + s2 for s1, s2 in zip(arr1, arr2)])
    
    return concatenated_array

# Given NumPy arrays of strings
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Concatenate strings element-wise
result = concatenate_strings(arr1, arr2)

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nConcatenated array:")
print(result)


Array 1:
['Hello' 'World']

Array 2:
['Open' 'AI']

Concatenated array:
['HelloOpen' 'WorldAI']


Q60. Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [14]:
def longest_str(arr):
    max_length=max((len(s)) for s in arr)
    return "The longest string length is", max_length

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_str(arr)          

('The longest string length is', 9)

Q61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.

In [19]:
np.random.seed(0) # Set seed for reproducibility (optional)

# Generate dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Compute mean, median, variance, and standard deviation
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)
print("Dataset\n",dataset)
print("\nThe mean of dataset is",mean)
print("\n The median of dataset is",median)
print("\n The variance of dataset is",variance)
print("\n The standard deviation of dataset is",std_deviation)

Dataset
 [ 685  560  630  193  836  764  708  360   10  724  278  755  805  600
   71  473  601  397  315  706  487  552   88  175  601  850  678  538
  846   73  778  917  116  977  756  710  848  432  449  851  100  985
  178  756  798  660  148  911  424  289  962  266  698  640  545  544
  715  245  152  676  511  460  883  184   29  803  129  129  933   54
  902  551  489  757  274  336  389  618   43  443  544  889  258  322
 1000  938   58  292  871  120  780  431   83   92  897  399  612  566
  909  634]

The mean of dataset is 524.97

 The median of dataset is 551.5

 The variance of dataset is 82414.08910000001

 The standard deviation of dataset is 287.07854169199067


62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.

In [23]:
arr=np.array([np.random.randint(1,100,50)])
np.percentile(arr,25)

26.25

In [24]:
np.percentile(arr,75)

70.5

Q63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.

In [26]:
arr1=([1,3,5])
arr2=([-2,8,12])
np.corrcoef(arr1,arr2)

array([[1.        , 0.97072534],
       [0.97072534, 1.        ]])

Q64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [31]:
m1=np.matrix([[1,2,3],
             [4,5,6],
             [7,8,9]])
m2=np.matrix([[1,2,2],
             [2,1,2],
             [1,3,2]])
res=m1.dot(m2)
print(res)

[[ 8 13 12]
 [20 31 30]
 [32 49 48]]


65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.

In [33]:
arr=np.array([np.random.randint(10,1001,50)])
print(arr)
print("The 10th percentile is",np.percentile(arr,10))
print("The 90th percentile is",np.percentile(arr,90))
print("The median(50th percentile) is",np.median(arr))
print("The first quartile(25th percentile) is",np.percentile(arr,25))
print("The third quartile(75th percentile) is",np.percentile(arr,75))

[[923  74 537 460 871 881 951 196 812 904  87 444 133 744 973 363 832 126
  237 325 646 413  14 213 188 943 600 185 470 880 692 827 550 606 234 885
  912 646 472 762 239 450 322 695 780 958 851 549 889 871]]
The 10th percentile is 179.8
The 90th percentile is 913.1
The median(50th percentile) is 603.0
The first quartile(25th percentile) is 322.75
The third quartile(75th percentile) is 866.0


66. Create a NumPy array of integers and find the index of a specific element.

In [35]:
array = np.array([10, 20, 30, 40, 50])

# Find the index of a specific element (e.g., 30)
element_to_find = 30
index = np.where(array == element_to_find)[0]

if index.size == 0:
    print(f"The element {element_to_find} is not found in the array.")
else:
    print(f"The index of {element_to_find} in the array is: {index[0]}")

The index of 30 in the array is: 2


Q67. Generate a random NumPy array and sort it in ascending order

In [39]:
arr=np.array([np.random.randint(1,10,8)])
sorted_arr=np.sort(arr)
print("The original array is",arr)
print("The sorted array is", sorted_arr)

The original array is [[2 5 9 8 3 6 3 2]]
The sorted array is [[2 2 3 3 5 6 8 9]]


Q68. Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])

In [46]:
arr = np.array([12, 25, 6, 42, 8, 30])
filter_arr=arr[arr>20]
print("The filtered elements>20 are", filter_arr)

The filtered elements>20 are [25 42 30]


Q69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])

In [53]:
arr = np.array([1, 5, 8, 12, 15])
filter_arr=arr[arr%3==0]
print("The filteredelements which are divisible by 3 are", filter_arr)

The filteredelements which are divisible by 3 are [12 15]


Q70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

In [56]:
arr = np.array([10, 20, 30, 40, 50])

# Filter elements between 20 and 40 (inclusive)
filtered_array = arr[(arr >= 20) & (arr <= 40)]

print("Original array:", arr)
print("Filtered elements between 20 and 40 (inclusive):", filtered_array)


Original array: [10 20 30 40 50]
Filtered elements between 20 and 40 (inclusive): [20 30 40]


Q71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])

In [57]:
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder

print("Byte order:", byte_order)

Byte order: =


Q72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [68]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr_swap=arr.byteswap()
print("Byte swapped array",arr_swap)

Byte swapped array [16777216 33554432 50331648]


Q73. For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [69]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr_swap=arr.newbyteorder()
print("Original array",arr)
print("Byte swapped array",arr_swap)

Original array [1 2 3]
Byte swapped array [16777216 33554432 50331648]


Q74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [70]:
arr = np.array([1, 2, 3], dtype=np.int32)

# Swap byte order conditionally based on system endianness
arr = arr.newbyteorder() if arr.dtype.byteorder != '=' else arr

print("Array with swapped byte order:", arr)

Array with swapped byte order: [1 2 3]


Q75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [71]:
arr = np.array([1, 2, 3], dtype=np.int32)

# Check if byte swapping is necessary
byte_swapping_needed = arr.dtype.byteorder != '='

if byte_swapping_needed:
    print("Byte swapping is necessary for the current system.")
else:
    print("Byte swapping is not necessary for the current system.")

Byte swapping is not necessary for the current system.


Q76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [73]:
arr1=np.array(np.arange(1,11))
copy_arr=arr1.copy()
copy_arr[1]=100
print("The original array is", arr1)
print("The copied and modified array is", copy_arr)

The original array is [ 1  2  3  4  5  6  7  8  9 10]
The copied and modified array is [  1 100   3   4   5   6   7   8   9  10]


Q77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [75]:
# Create a 2D NumPy array (matrix) of shape (3, 3) with random integers
matrix = np.random.randint(1, 10, size=(3, 3))
print("Original matrix:\n", matrix)

# Extract a slice (view_slice) from the matrix
view_slice = matrix[1:, 1:]
print("\nView slice from the matrix:")
print(view_slice)

# Modify an element in the view_slice
view_slice[0, 0] = 99

# Check if the modification reflects in the original matrix
print("\nModified view slice:")
print(view_slice)
print("\nOriginal matrix after modification:")
print(matrix)


Original matrix:
 [[5 3 2]
 [4 8 1]
 [6 7 4]]

View slice from the matrix:
[[8 1]
 [7 4]]

Modified view slice:
[[99  1]
 [ 7  4]]

Original matrix after modification:
[[ 5  3  2]
 [ 4 99  1]
 [ 6  7  4]]


Q78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [85]:
array_a=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [10,11,12]])
print("The original array before modification",array_a)
view_b=array_a[1:,1:]
print("\nExtracting slice array_a[1:,1:]",view_b)
view_b=view_b+5
print("\nview_b after broadcasting addition of 5",view_b) #view_b after broadcasting addition of 5
print("\nThe original array after modification",array_a)

The original array before modification [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Extracting slice array_a[1:,1:] [[ 5  6]
 [ 8  9]
 [11 12]]

view_b after broadcasting addition of 5 [[10 11]
 [13 14]
 [16 17]]

The original array after modification [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Q79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.

In [87]:
orig_array=np.array([[1,2,3,4],
                     [5,6,7,8]])
print("The originial array", orig_array)
reshaped_view=orig_array.reshape(4,2)
print("\n The reshaped array", reshaped_view)
reshaped_view[0,0]=100
print("\n The reshaped arrayafter modifying an element", reshaped_view)
print("The originial array after changes", orig_array)

The originial array [[1 2 3 4]
 [5 6 7 8]]

 The reshaped array [[1 2]
 [3 4]
 [5 6]
 [7 8]]

 The reshaped arrayafter modifying an element [[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]
The originial array after changes [[100   2   3   4]
 [  5   6   7   8]]


Q80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [94]:
data=np.random.randint(1,11,size=(3,4))
print("The original array\n",data)
data_copy=np.copy(data[data>5])
print("Extracting elements greater than 5\n", data_copy)
data_copy[0]=1000
print("\nmodified extracted array\n",data_copy)
print("\nOriginial array after the process\n", data)

The original array
 [[10  3  4  3]
 [ 2  7  9  9]
 [ 6  9  2 10]]
Extracting elements greater than 5
 [10  7  9  9  6  9 10]

modified extracted array
 [1000    7    9    9    6    9   10]

Originial array after the process
 [[10  3  4  3]
 [ 2  7  9  9]
 [ 6  9  2 10]]


Q81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.

In [4]:
mat_A=np.random.randint(1,10,size=(3,3))
print("Matrix A \n",mat_A)
mat_B=np.random.randint(1,10,size=(3,3))
print("Matrix B \n",mat_B)
add=mat_A+mat_B
print("Matrix A+ Matrix B=\n",add)
sub=mat_A-mat_B
print("Matrix A-Matrix B=\n",sub)

Matrix A 
 [[6 8 1]
 [4 1 4]
 [1 1 3]]
Matrix B 
 [[9 3 1]
 [1 9 7]
 [5 1 6]]
Matrix A+ Matrix B=
 [[15 11  2]
 [ 5 10 11]
 [ 6  2  9]]
Matrix A-Matrix B=
 [[-3  5  0]
 [ 3 -8 -3]
 [-4  0 -3]]


Q82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [7]:
mat_C=np.random.randint(1,10,size=(3,2))
print("Matrix C \n",mat_C,"\n having size", mat_C.shape)
mat_D=np.random.randint(1,10,size=(2,4))
print("Matrix D \n",mat_D,"\n having size", mat_D.shape)
mat_mul=mat_C@mat_D
print("The result of matrix multiplication is\n", mat_mul)

Matrix C 
 [[1 2]
 [8 9]
 [1 9]] 
 having size (3, 2)
Matrix D 
 [[3 7 7 9]
 [6 7 1 7]] 
 having size (2, 4)
The result of matrix multiplication is
 [[ 15  21   9  23]
 [ 78 119  65 135]
 [ 57  70  16  72]]


Q83. Create a matrix `E` and find its transpose.

In [8]:
mat_E=np.random.randint(1,10,size=(4,2))
print("The matrix E is \n", mat_E)
print("The transposed matrix is\n",mat_E.T)

The matrix E is 
 [[6 4]
 [8 9]
 [6 1]
 [9 8]]
The transposed matrix is
 [[6 8 6 9]
 [4 9 1 8]]


Q84. Generate a square matrix `F` and compute its determinant.

In [9]:
mat_F=np.random.randint(1,10,size=(3,3))
print("The matrix F is\n",mat_F)
det=np.linalg.det(mat_F)
print("Determinant of matrix F is\n", det)

The matrix F is
 [[7 9 1]
 [7 4 4]
 [9 6 4]]
Determinant of matrix F is
 22.000000000000036


85. Create a square matrix `G` and find its inverse.

In [10]:
mat_G=np.random.randint(1,10,size=(3,3))
print("The matrix G is\n",mat_G)
inv=np.linalg.inv(mat_F)
print("The inverse of matrix G is\n", inv)

The matrix G is
 [[9 7 1]
 [1 3 4]
 [9 1 9]]
The inverse of matrix G is
 [[-0.36363636 -1.36363636  1.45454545]
 [ 0.36363636  0.86363636 -0.95454545]
 [ 0.27272727  1.77272727 -1.59090909]]
